### ISSUE TITLE
Cannot load module 'IntuneMAMWalledGardenSwift' as 'IntuneMAMSwift'

### ISSUE THREAD

**Issue by leonzhuyihong** [msintuneappsdk/Chatr-Sample-Intune-iOS-App#50] opened 2019-10-02 08:25 UTC
Hi All,

When I download zip file and open in Xcode 10.2.1, I got this error. 

I didn't change anything.
Cannot load module 'IntuneMAMWalledGardenSwift' as 'IntuneMAMSwift'

Could you please suggest? 

Meanwhile, could i please know if it support Xcode 11 now?
<img width="1018" alt="截屏2019-10-02下午4 24 28" src="https://user-images.githubusercontent.com/3906787/66029089-29442200-e531-11e9-9192-d35e7553e860.png">

**Comment by slnali** [comment] 2019-10-02 12:02
Xcode 11 is not supported on current version of sdk: https://github.com/msintuneappsdk/Chatr-Sample-Intune-iOS-App/issues/48 

Regarding this error: I solved by updating the IntuneMAMSwift.framework and IntuneMAMSwiftStub.framework to the latest version (11.2.0 has the fix). You can use a dependency manager (cocapods) but I manually copied it over by downloading this zip for sdk and replacing the framework files with the update versions here: https://github.com/msintuneappsdk/ms-intune-app-sdk-ios

![image](https://user-images.githubusercontent.com/9381704/66042587-c0e74780-e514-11e9-9896-7d3a82853945.png)

**Comment by Kyle-Reis** [comment] 2019-10-02 14:36
Hey @leonzhuyihong, this is a [known issue](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/47) in version 11.1.2 of the SDK which we addressed in version 11.2.0. The issue is specific to simulator, so you should be able to build for a physical device. Alternatively, you can upgrade to 11.2.0 to build for both simulator and device.

Note: As @slnali mentioned, you'll need to build with Xcode 10 for now as we have not yet released a version of our SDK which supports Xcode 11. We're working on addressing that and will update the sample repo as soon as that happens.

**Comment by leonzhuyihong** [comment] 2019-10-02 14:56
Hi All,

Appreciate of prompt reply!

Just replace SDK to 11.2.0 and error gone.

Thanks All!

**Comment by Kyle-Reis** [comment] 2019-10-08 17:49
Hey @leonzhuyihong, I just updated the sample to use the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) of the Intune MAM SDK (12.0.12), which supports Xcode 11. Both issues should be resolved now.

**Closed by Kyle-Reis** 2019-10-08 17:49 UTC
